apiVersion: v1
kind: Service
metadata:
  name: djrestapi-service
spec:
  selector:
    app: djrestapi
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: djrestapi
spec:
  selector:
    matchLabels:
      app: djrestapi
  replicas: 2
  template:
    metadata:
      labels:
        app: djrestapi
    spec:
      containers:
      - name: djrestapi
        image: tvrajah/djrestapi
        imagePullPolicy: Never
        ports:
        - containerPort: 5000