trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1f79ead0-c06b-43e2-ac72-c0174d30d14b'
  imageRepository: 'acraussiestocktraderservice'
  containerRegistry: 'acraussiestocktrader.azurecr.io'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'azure-resource-manager-service-connection'
        appName: 'djrestapi'
        containers: 'djrestapi'
        multicontainerConfigFile: '**/docker-compose.yml'
        containerCommand: 'docker compose up'
        appSettings: '-Port 8000'